name: Run Selenium Script

on:
  push:
    branches:
      - main

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Run Selenium script
      run: python m3u8/extract.py

    - name: Upload tvs_token.txt
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: tvs_token
        path: tvs_token.txt
