name: Extract Session ID

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  extract_session_id:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      - name: Run extraction script
        run: python extract.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add tvs_token.txt
          git commit -m 'Update tvs_token'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
