name: Generate M3U File

on:
  schedule:
    - cron: '* */4 * * *'
  workflow_dispatch:

#  push:
#    branches:
#      - main  # Trigger on push to the main branch as well


jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0 

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Run PHP script
      run: |
        php generate.php || exit 1  # Fail the workflow if PHP script fails

    - name: Squash and force push changes
      if: success()
      run: |
        # Setting up git config
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

        # Reset to the first commit
        FIRST_COMMIT=$(git rev-list --max-parents=0 HEAD)
        git reset --soft $FIRST_COMMIT

        # Add all changes and create a single new commit
        git add streamedsu.m3u8
        git commit -m "Update M3U" || echo "No changes to commit"

        # Force push to the main branch
        git push -f origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
